In [1]:
import warnings
warnings.filterwarnings(action='ignore')
%config Computer.use_jedi = False
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'NanumGothicCoding'
plt.rcParams['font.size'] = 15
import seaborn as sns
from plotnine import *
import missingno as msno

영업 중인 전국 상가 업소 동향  
공공데이터포털(https://www.data.go.kr/)에서 '소상공인시장진흥공단' 검색

<img src='./images/소상공인시장진흥공단1.png' align="left" width="1100"/>

<img src='./images/소상공인시장진흥공단2.png' align="left" width="1100"/>

소상공인시장진흥공단_상가(상권)정보 중에서 서울과 부산 데이터만 읽어서 하나의 데이터프레임으로 만들어 csv 파일로 만들어 저장한다.

In [8]:
# shop_2022_seoul = pd.read_csv('./data/shop_2022_seoul.csv')
# print(shop_2022_seoul.shape)
# shop_2022_seoul.head()

(377724, 39)

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,23324279,제중건강원,NaN,D,소매,D10,건강/미용식품,D10A07,건강원,G47216,...,1156010600100410002034626,NaN,서울특별시 영등포구 영중로14길 11-17,150035,7250.0,NaN,1,NaN,126.907168,37.520613
1,24525909,민속악기사,NaN,D,소매,D04,취미/오락관련소매,D04A09,악기판매,G47593,...,1120012200101420011000227,NaN,서울특별시 성동구 용답5길 2,133849,4803.0,NaN,NaN,NaN,127.049018,37.566857
2,24715368,태평양진주,NaN,D,소매,D26,시계/귀금속소매,D26A01,시계/귀금속,G47830,...,1111015200100440000000001,금사랑투빌딩,서울특별시 종로구 서순라길 17-10,110390,3138.0,NaN,NaN,NaN,126.993530,37.571848
3,15554136,김선희꼼꼼국어교습소,NaN,R,학문/교육,R01,학원-보습교습입시,R01A01,학원-입시,P85501,...,1171011100101970003017195,NaN,서울특별시 송파구 위례성대로12길 31,138834,5640.0,NaN,2,NaN,127.121520,37.510967
4,17174175,비지트,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1165010100108540018009586,상랑의빌딩,서울특별시 서초구 동광로18길 82,137837,6572.0,NaN,1,NaN,126.991394,37.488375

In [9]:
# shop_2022_busan = pd.read_csv('./data/shop_2022_busan.csv')
# print(shop_2022_busan.shape)
# shop_2022_busan.head()

(162560, 39)

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,23206623,미광장,NaN,O,숙박,O02,모텔/여관/여인숙,O02A01,모텔/여관/여인숙,I55112,...,2611012600100250001004473,NaN,부산광역시 중구 보수대로44번길 5,600074,48974.0,NaN,NaN,NaN,129.023668,35.100979
1,20418637,BHC치킨,동래점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2626010500101850000016529,NaN,부산광역시 동래구 동래로147번길 18,607020,47802.0,NaN,NaN,NaN,129.087156,35.205267
2,24659633,스텔라,NaN,D,소매,D05,의복의류,D05A01,일반의류,G47416,...,2650010500101480004001694,비치아파트,부산광역시 수영구 광안해변로 100,613751,48305.0,NaN,NaN,NaN,129.115397,35.143770
3,17174094,도란도란,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,2623011100101740004050547,NaN,부산광역시 부산진구 가야대로482번길 29-3,614813,47327.0,NaN,NaN,NaN,129.024938,35.151645
4,21683903,럭키사진관,NaN,F,생활서비스,F06,사진,F06A01,사진관,M73301,...,2638010200103250030010858,NaN,부산광역시 사하구 낙동대로 395,604830,49411.0,NaN,1,NaN,128.974794,35.102905

In [10]:
# shop_2022 = pd.concat([shop_2022_seoul, shop_2022_busan], axis=0, ignore_index=True)
# shop_2022

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,23324279,제중건강원,NaN,D,소매,D10,건강/미용식품,D10A07,건강원,G47216,...,1156010600100410002034626,NaN,서울특별시 영등포구 영중로14길 11-17,150035,7250.0,NaN,1,NaN,126.907168,37.520613
1,24525909,민속악기사,NaN,D,소매,D04,취미/오락관련소매,D04A09,악기판매,G47593,...,1120012200101420011000227,NaN,서울특별시 성동구 용답5길 2,133849,4803.0,NaN,NaN,NaN,127.049018,37.566857
2,24715368,태평양진주,NaN,D,소매,D26,시계/귀금속소매,D26A01,시계/귀금속,G47830,...,1111015200100440000000001,금사랑투빌딩,서울특별시 종로구 서순라길 17-10,110390,3138.0,NaN,NaN,NaN,126.993530,37.571848
3,15554136,김선희꼼꼼국어교습소,NaN,R,학문/교육,R01,학원-보습교습입시,R01A01,학원-입시,P85501,...,1171011100101970003017195,NaN,서울특별시 송파구 위례성대로12길 31,138834,5640.0,NaN,2,NaN,127.121520,37.510967
4,17174175,비지트,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1165010100108540018009586,상랑의빌딩,서울특별시 서초구 동광로18길 82,137837,6572.0,NaN,1,NaN,126.991394,37.488375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540279,19076189,리오마죠레,NaN,F,생활서비스,F01,이/미용/건강,F01A01,여성미용실,S96112,...,2635010300116320000000001,아시아선수촌프레스센터상가,부산광역시 해운대구 반여로 131,612061,48037.0,NaN,1,NaN,129.123373,35.203476
540280,19076390,메이미래쉬,NaN,F,생활서비스,F01,이/미용/건강,F01A03,비만/피부관리,NaN,...,2644011400111900002000002,NaN,부산광역시 강서구 과학산단로334번다길 60,618210,46743.0,NaN,1,NaN,128.835928,35.149797
540281,19077180,크라운호프,부산학장점,Q,음식,Q09,유흥주점,Q09A01,호프/맥주,I56219,...,2653010700201450017006118,NaN,부산광역시 사상구 대동로 111,617846,47050.0,NaN,3,NaN,128.979739,35.139354
540282,19077185,가배원커피,당리점,Q,음식,Q12,커피점/카페,Q12A01,커피전문점/카페/다방,I56220,...,2638010300106230017000001,NaN,부산광역시 사하구 낙동대로 413,604848,49410.0,101,1,NaN,128.973045,35.103424
540283,19078983,덴텍스,NaN,D,소매,D03,종합소매점,D03A05,수입품판매점,G47190,...,2611010800100230000006805,경보이리스오션더스타,부산광역시 중구 대교로 133,600015,48943.0,NaN,NaN,NaN,129.037433,35.101818

In [11]:
# 서울과 부산 데이터만 읽어서 하나의 데이터프레임으로 만든 데이터를 csv 파일로 저장한다.
# csv 파일로 저장할 때 인덱스를 제외하고 저장하려면 index=None 옵션을 사용한다.
# shop_2022.to_csv('./data/shop_2022.csv', index=None)

In [12]:
# 파이썬은 java 처럼 {} 블록이 없어서 사용한 변수가 자동으로 삭제되지 않기때문에 계속 메모리를 차지하는 문제가 발생될 수 있으므로
# del 명령을 실행해서 사용하지 않는 변수는 메모리에서 삭제한다.
# del shop_2022_seoul, shop_2022_busan